server:
  port: 10803

spring:
  application:
    name: product-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.138.130:8848

    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: 192.168.138.130:8858

feign:
  sentinel:
    enabled: true