server:
  port: 10803
  servlet:
    context-path: /api/product

spring:
  application:
    name: product-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.138.131:8848

    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: 192.168.138.131:8858

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        requestInterceptors:
          - com.herring.feign.interceptor.TokenRelayRequestInterceptor

rocketmq:
  name-server: 192.168.138.131:9876
  producer:
    group: product-group

seata:
  tx-service-group: herring_group

  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.138.131:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos

  config:
    type: nacos
    nacos:
      server-addr: 192.168.138.131:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos