server:
  port: 10802

spring:
  application:
    name: orders-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.138.131:8848

    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: 192.168.138.131:8858

feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: 192.168.138.131:9876
  producer:
    group: orders-group